apiVersion: v1
kind: Service
metadata:
  name: shs
  namespace: bigdata
spec:
  ports:
  - port: 18080
    protocol: TCP
    targetPort: 18080
  selector:
    run: spark-history-server
  type: NodePort
