apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 200Gi  # 设置存储容量大小
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # 设置适合您需求的访问模式
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: rtduat.file.core.windows.net  # 替换为实际的 NFS 服务器 IP 地址
    path: /rtduat/middleware/zk  # 替换为实际的 NFS 共享路径