apiVersion: v1
data:
  mysql.db.name: nacos
  mysql.host: MYSQL_IP
  mysql.password: MYSQL_PASS
  mysql.port: "3306"
  mysql.user: MYSQL_USER
  nacos_datasource_platform: mysql
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: kt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: kt
  labels:
    app: nacos
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nacos
  #serviceName: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - env:
        - name: NACOS_REPLICAS
          value: "1"
        - name: MYSQL_SERVICE_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: mysql.db.name
              name: nacos-config
              optional: false
        - name: MYSQL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: mysql.port
              name: nacos-config
              optional: false
        - name: MYSQL_SERVICE_USER
          valueFrom:
            configMapKeyRef:
              key: mysql.user
              name: nacos-config
              optional: false
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: mysql.password
              name: nacos-config
              optional: false
        - name: NACOS_SERVER_PORT
          value: "8848"
        - name: NACOS_APPLICATION_PORT
          value: "8848"
        - name: PREFER_HOST_MODE
          value: hostname
        - name: MODE
          value: standalone  
        - name: MYSQL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              key: mysql.host
              name: nacos-config
              optional: false
        - name: SPRING_DATASOURCE_PLATFORM
          valueFrom:
            configMapKeyRef:
              key: nacos_datasource_platform
              name: nacos-config
              optional: false
        image: ktsoft-docker.pkg.coding.net/yongce/kt-public-image/nacos:2.0.3
        imagePullPolicy: IfNotPresent
        name: k8snacos
        ports:
        - containerPort: 8848
          name: client
          protocol: TCP
        - containerPort: 7848
          name: rpc
          protocol: TCP
        - containerPort: 9848
          name: port9848
          protocol: TCP
        resources:
          requests:
            memory: 2Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: coding-docker-pull-private
    
#集群模式的话，更改- name: MODE
#        - name: NACOS_SERVERS
#          value: nacos-0.nacos.default.svc.cluster.local:8848 nacos-1.nacos.default.svc.cluster.local:8848 
#nacos数据目录：
#/home/nacos/conf
#/home/nacos/logs 
#/home/nacos/data
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: kt
  labels:
    app: nacos
spec:
  type: NodePort
  ports:
  - name: server
    port: 8848
    targetPort: 8848
    protocol: TCP
    nodePort: 30210
  - name: port9848
    port: 9848
    targetPort: 9848
    protocol: TCP
    nodePort: 31210
  selector:
    app: nacos
