apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: pulsar
  namespace: kt
  labels:
    app: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
    #  nodeSelector:
    #    env: test-team
      containers:
      - name: pulsar
        image: ktsoft-docker.pkg.coding.net/yongce/kt-public-image/pulsar:private
        args:
          - /bin/bash
          - '-c'
          - "bin/pulsar standalone"
        ports:
        - containerPort: 6650
        - containerPort: 8080
       # resources:
         # limits:
          #  cpu: "200m"
        volumeMounts:
        - name: data
          mountPath: /pulsar/data
        - name: conf
          mountPath: /pulsar/conf
      volumes:
      - name: data
        hostPath:
          path: IM_PATH_PULSAR_DATA
          type: DirectoryOrCreate
      - name: conf
        hostPath:
          path: IM_PATH_PULSAR_CONF
          type: DirectoryOrCreate
      nodeName: IM_NODE
      imagePullSecrets:
      - name: coding-docker-pull-private
#注意 需要挂载存储卷，使用pvc或是主机挂在卷

---
apiVersion: v1
kind: Service
metadata:
  name: pulsar
  namespace: kt
  labels:
    app: pulsar
spec:
  type: NodePort
  ports:
  - name:  server-6650
    port: 6650
    targetPort: 6650
    protocol: TCP
    nodePort: 30211
  - name: web-8080
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30233
  selector:
    app: pulsar	
