apiVersion: v1
data:
  redis.conf: |-
    #端口 6379
    port 6379
    #yes 设置后台运行
    daemonize no
    #database 200
    #设置pidfile存放在 run目录下的文件名
    pidfile  /data/redis_6379.pid
    #指定数据文件存放位置，必须要指定不同的目录位置，不然会丢失数据
    dir /data
    #设置开启rbd模式
    save 900 1
    save 300 10
    save 60 100
    dbfilename redis.rdb
    #启动集群
    cluster-enabled no
    #关联集群节点信息文件
    #cluster-config-file /data/redis-cluster/nodes-6379.conf
    #设置超时
    cluster-node-timeout 5000
    #关闭保护模式
    protected-mode no 
    #日志信息，可有可无
    #logfile /data/redis.log
    #指定ip访问的地址，设置0.0.0.0 默认是全部地址，不设置，后面会连接不上的
    bind 0.0.0.0
    #密码
    requirepass VBC0#Rr5qw
    masterauth VBC0#Rr5qw
kind: ConfigMap
metadata:
  name: redis-conf
  namespace: kt
 
---	  
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: kt
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: ktsoft-docker.pkg.coding.net/yongce/kt-public-image/redis:private
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - redis-server "/mnt/redis.conf"
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 1536Mi
          requests:
            memory: 1024Mi
        volumeMounts:
          - name: redis-conf
            mountPath: /mnt
          - name: data
            mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: IM_REDIS_PATH
          type: DirectoryOrCreate
      - name: redis-conf
        configMap:
          name: redis-conf
      nodeName: IM_NODE
      imagePullSecrets:
      - name: coding-docker-pull-private
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kt
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - name:  server-redis
    port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 30212
  selector:
    app: redis
