apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
spec:
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
      - name: xxl-job-admin
        image: ktsoft-docker.pkg.coding.net/yongce/kt-public-image/xxl-job-admin-2.3.0:private
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: port8080
          protocol: TCP
        env:
        - name: PARAMS
          value: "--spring.datasource.url=jdbc:mysql://MYSQL_IP:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false --spring.datasource.username=MYSQL_USER  --spring.datasource.password=MYSQL_PASS"	#根据情况修改数据库连接信息
      imagePullSecrets:
      - name: coding-docker-pull-private

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xxl-job-admin
  name: xxl-job-admin
spec:
  ports:
    - name: port8080
      nodePort: 30128
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: xxl-job-admin
  type: NodePort





